package com.pilers.errors;

/**
 * A CompileException is thrown during the semantic analysis of compilation
 * It can occur for a variety of reasons, including type and scope errors
 * 
 * When throwing a CompileException error, a string generated by the ErrorString
 * class should be passed in.
 * 
 * @author Gloria Zhu
 */
public class CompileException extends Exception
{
    // satisfy inheritance
    private static final long serialVersionUID = 1L;

    /**
     * Constructor for CompileException that includes a reason for the error
     * 
     * This should always be called using one of the static reason generators in the
     * ErrorString class
     * 
     * @param reason the reason for the CompileException
     */
    public CompileException(String reason)
    {
        super(reason);
    }

}