package com.pilers.errors;

/**
 * An InterpretException is thrown during the runtime of interpretation It can
 * occur for a variety of reasons, including type and scope errors
 * 
 * When throwing an InterpretException error, a string generated by the
 * ErrorString class should be passed in.
 * 
 * @author Gloria Zhu
 */
public class InterpretException extends Exception
{

    // satisfy inheritance
    private static final long serialVersionUID = 1L;

    /**
     * Constructor for InterpretException that includes a reason for the error
     * 
     * This should always be called using one of the static reason generators in the
     * ErrorString class
     * 
     * @param reason the reason for the InterpretException
     */
    public InterpretException(String reason)
    {
        super(reason);
    }
}