package com.pilers.errors;

/**
 * A PreprocessorException is thrown during the preprocessing phase of
 * the compiler
 * It can be thrown for a variety of reasons, such as unknown directives
 * 
 * When throwing a PreprocessorException error, a string generated by the
 * ErrorString class should be passed in.
 * 
 * @author Gloria Zhu
 */
public class PreprocessorException extends Exception
{
    // satisfy inheritance
    private static final long serialVersionUID = 1L;

    /**
     * Constructor for PreprocessorException that includes a reason for the error
     * 
     * This should always be called using one of the static reason generators in the
     * ErrorString class
     * 
     * @param reason the reason for the PreprocessorException
     */
    public PreprocessorException(String reason)
    {
        super(reason);
    }

}